---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: cargo
    directory: "/bessel_rust"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: direct
      - dependency-type: indirect
